title: Vratislav Bělský
# subtitle: Hudební oddělení - Programové oddělení
author: 
  name: Hudební oddělení MZK
  email: hudebni@mzk.cz

description: >
 Vratislav Bělský - Multimediální výstava


theme: minima


minima:


header_pages:
  - about.md
  - test.md

collections:
  - belsky

permalink: /:title

google_analytics: G-Q0K6ZELB9Y